// Generated by InferSynth emit_sysc_ams — do not edit.
// Cell testbench: opamp-gain-noninverting
//
// Drives a sine into each electrical input and a DC level onto each rail,
// runs the AMS TDF module, and records t + inputs + outputs to CSV. The
// operating point mirrors the v0 `linear` scenario (docs/SIM.md).
#include <systemc-ams>
#include <cmath>
#include <fstream>
#include <string>
#include "opamp-gain-noninverting.h"

// Deterministic stimulus sources (stateless: pure functions of TDF time).
SCA_TDF_MODULE(is_sine_src)
{
    sca_tdf::sca_out<double> out;
    const double amplitude;
    const double freq_hz;
    const double offset;
    const double timestep_s;

    is_sine_src(sc_core::sc_module_name nm, double amplitude_, double freq_hz_,
                double offset_, double timestep_s_)
        : out("out"), amplitude(amplitude_), freq_hz(freq_hz_), offset(offset_),
          timestep_s(timestep_s_)
    {
    }

    void set_attributes() { set_timestep(timestep_s, sc_core::SC_SEC); }

    void processing()
    {
        const double t = get_time().to_seconds();
        out.write(offset + amplitude * std::sin(2.0 * M_PI * freq_hz * t));
    }
};

SCA_TDF_MODULE(is_dc_src)
{
    sca_tdf::sca_out<double> out;
    const double value;
    const double timestep_s;

    is_dc_src(sc_core::sc_module_name nm, double value_, double timestep_s_)
        : out("out"), value(value_), timestep_s(timestep_s_)
    {
    }

    void set_attributes() { set_timestep(timestep_s, sc_core::SC_SEC); }

    void processing() { out.write(value); }
};

// CSV trace recorder: writes one row per timestep (no header row here).
SCA_TDF_MODULE(is_trace_recorder)
{
    sca_tdf::sca_in<double> IN;
    sca_tdf::sca_in<double> OUT;
    std::ofstream &os;

    is_trace_recorder(sc_core::sc_module_name nm, std::ofstream &os_)
        : IN("IN"), OUT("OUT"), os(os_)
    {
    }

    void processing()
    {
        os << get_time().to_seconds() << "," << IN.read() << "," << OUT.read() << "\n";
    }
};

int sc_main(int argc, char *argv[])
{
    const std::string out_path = (argc > 1) ? argv[1] : "trace.csv";

    // One signal per cell port.
    sca_tdf::sca_signal<double> sig_IN;
    sca_tdf::sca_signal<double> sig_OUT;
    sca_tdf::sca_signal<double> sig_GND;
    sca_tdf::sca_signal<double> sig_VCC;
    sca_tdf::sca_signal<double> sig_VEE;

    // Stimulus: a sine per input, a DC level per rail.
    is_sine_src src_IN("src_IN", 1.0, 1000.0, 0.0, 1e-06);
    src_IN.out(sig_IN);
    is_dc_src src_GND("src_GND", 0.0, 1e-06);
    src_GND.out(sig_GND);
    is_dc_src src_VCC("src_VCC", 12.0, 1e-06);
    src_VCC.out(sig_VCC);
    is_dc_src src_VEE("src_VEE", -12.0, 1e-06);
    src_VEE.out(sig_VEE);

    // Device under test.
    opamp_gain_noninverting dut("dut", 4.0, 0.1);
    dut.IN(sig_IN);
    dut.OUT(sig_OUT);
    dut.GND(sig_GND);
    dut.VCC(sig_VCC);
    dut.VEE(sig_VEE);

    // CSV trace.
    std::ofstream os(out_path.c_str());
    os << "t,IN,OUT\n";
    is_trace_recorder rec("rec", os);
    rec.IN(sig_IN); rec.OUT(sig_OUT);

    sc_core::sc_start(0.001, sc_core::SC_SEC);
    os.close();
    return 0;
}
