// Generated by InferSynth emit_sysc_ams — do not edit.
// Cell testbench: opamp-gain-x4-noninverting
//
// Drives a sine into each electrical input and a DC level onto each rail,
// runs the AMS TDF module, and records t + inputs + outputs to CSV. The
// operating point mirrors the v0 `linear` scenario (docs/SIM.md).
#include <systemc-ams>
#include <cmath>
#include <fstream>
#include <string>
#include "opamp-gain-x4-noninverting.h"

// Deterministic stimulus sources (stateless: pure functions of TDF time).
SCA_TDF_MODULE(is_sine_src)
{
    sca_tdf::sca_out<double> out;
    const double amplitude;
    const double freq_hz;
    const double offset;
    const double timestep_s;

    is_sine_src(sc_core::sc_module_name nm, double amplitude_, double freq_hz_,
                double offset_, double timestep_s_)
        : out("out"), amplitude(amplitude_), freq_hz(freq_hz_), offset(offset_),
          timestep_s(timestep_s_)
    {
    }

    void set_attributes() { set_timestep(timestep_s, sc_core::SC_SEC); }

    void processing()
    {
        const double t = get_time().to_seconds();
        out.write(offset + amplitude * std::sin(2.0 * M_PI * freq_hz * t));
    }
};

SCA_TDF_MODULE(is_dc_src)
{
    sca_tdf::sca_out<double> out;
    const double value;
    const double timestep_s;

    is_dc_src(sc_core::sc_module_name nm, double value_, double timestep_s_)
        : out("out"), value(value_), timestep_s(timestep_s_)
    {
    }

    void set_attributes() { set_timestep(timestep_s, sc_core::SC_SEC); }

    void processing() { out.write(value); }
};

// CSV trace recorder: writes one row per timestep (no header row here).
SCA_TDF_MODULE(is_trace_recorder)
{
    sca_tdf::sca_in<double> IN1;
    sca_tdf::sca_in<double> IN2;
    sca_tdf::sca_in<double> IN3;
    sca_tdf::sca_in<double> IN4;
    sca_tdf::sca_in<double> OUT1;
    sca_tdf::sca_in<double> OUT2;
    sca_tdf::sca_in<double> OUT3;
    sca_tdf::sca_in<double> OUT4;
    std::ofstream &os;

    is_trace_recorder(sc_core::sc_module_name nm, std::ofstream &os_)
        : IN1("IN1"), IN2("IN2"), IN3("IN3"), IN4("IN4"), OUT1("OUT1"), OUT2("OUT2"), OUT3("OUT3"), OUT4("OUT4"), os(os_)
    {
    }

    void processing()
    {
        os << get_time().to_seconds() << "," << IN1.read() << "," << IN2.read() << "," << IN3.read() << "," << IN4.read() << "," << OUT1.read() << "," << OUT2.read() << "," << OUT3.read() << "," << OUT4.read() << "\n";
    }
};

int sc_main(int argc, char *argv[])
{
    const std::string out_path = (argc > 1) ? argv[1] : "trace.csv";

    // One signal per cell port.
    sca_tdf::sca_signal<double> sig_IN1;
    sca_tdf::sca_signal<double> sig_IN2;
    sca_tdf::sca_signal<double> sig_IN3;
    sca_tdf::sca_signal<double> sig_IN4;
    sca_tdf::sca_signal<double> sig_OUT1;
    sca_tdf::sca_signal<double> sig_OUT2;
    sca_tdf::sca_signal<double> sig_OUT3;
    sca_tdf::sca_signal<double> sig_OUT4;
    sca_tdf::sca_signal<double> sig_GND;
    sca_tdf::sca_signal<double> sig_VCC;
    sca_tdf::sca_signal<double> sig_VEE;

    // Stimulus: a sine per input, a DC level per rail.
    is_sine_src src_IN1("src_IN1", 1.0, 1000.0, 0.0, 1e-06);
    src_IN1.out(sig_IN1);
    is_sine_src src_IN2("src_IN2", 1.0, 1000.0, 0.0, 1e-06);
    src_IN2.out(sig_IN2);
    is_sine_src src_IN3("src_IN3", 1.0, 1000.0, 0.0, 1e-06);
    src_IN3.out(sig_IN3);
    is_sine_src src_IN4("src_IN4", 1.0, 1000.0, 0.0, 1e-06);
    src_IN4.out(sig_IN4);
    is_dc_src src_GND("src_GND", 0.0, 1e-06);
    src_GND.out(sig_GND);
    is_dc_src src_VCC("src_VCC", 12.0, 1e-06);
    src_VCC.out(sig_VCC);
    is_dc_src src_VEE("src_VEE", -12.0, 1e-06);
    src_VEE.out(sig_VEE);

    // Device under test.
    opamp_gain_x4_noninverting dut("dut", 1.0, 2.0, 3.0, 4.0, 0.1);
    dut.IN1(sig_IN1);
    dut.IN2(sig_IN2);
    dut.IN3(sig_IN3);
    dut.IN4(sig_IN4);
    dut.OUT1(sig_OUT1);
    dut.OUT2(sig_OUT2);
    dut.OUT3(sig_OUT3);
    dut.OUT4(sig_OUT4);
    dut.GND(sig_GND);
    dut.VCC(sig_VCC);
    dut.VEE(sig_VEE);

    // CSV trace.
    std::ofstream os(out_path.c_str());
    os << "t,IN1,IN2,IN3,IN4,OUT1,OUT2,OUT3,OUT4\n";
    is_trace_recorder rec("rec", os);
    rec.IN1(sig_IN1); rec.IN2(sig_IN2); rec.IN3(sig_IN3); rec.IN4(sig_IN4); rec.OUT1(sig_OUT1); rec.OUT2(sig_OUT2); rec.OUT3(sig_OUT3); rec.OUT4(sig_OUT4);

    sc_core::sc_start(0.001, sc_core::SC_SEC);
    os.close();
    return 0;
}
