"""Tests for the SystemC-AMS emitter + kernel seam (WP-S2).

Covers: byte-stable golden emission for both op-amp cells, emission determinism,
the bundled AMS header matching the committed catalog artifact, design-level
structural emission with a loud stub gap, the toolchain probe (monkeypatched
present/absent), CSV parsing, the ``ams-simulation`` gate's two distinct loud
skips, and — under ``@pytest.mark.sysc_ams`` — the real compile+run+cross-check
against the v0 tier (skipped when no toolchain is present).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from infersynth.catalog.loader import load_cell
from infersynth.emit_sysc_ams import (
    AmsToolchain,
    detect_toolchain,
    emit_cell,
    emit_design,
    emit_makefile,
    parse_csv_trace,
    spec_from_cell,
)
from infersynth.emit_sysc_ams import toolchain as tc_mod
from infersynth.gates.ams_simulation import AMS_GATE, ams_simulation_cell_gate
from infersynth.gates.runner import GateStatus
from infersynth.ir.core import (
    BOUNDARY,
    Cell,
    Design,
    Param,
    Port,
    PortDirection,
    PortKind,
)
from infersynth.ir.elaborate import elaborate

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog" / "core"
GOLDEN = Path(__file__).resolve().parent / "fixtures" / "ams_golden"
NONINV = CATALOG / "opamp-gain-noninverting"
X4 = CATALOG / "opamp-gain-x4-noninverting"
DECOUPLING = CATALOG / "decoupling"

_CELLS = ("opamp-gain-noninverting", "opamp-gain-x4-noninverting")


# --------------------------------------------------------------------------- #
# Golden emission + determinism.                                               #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("name", _CELLS)
def test_cell_main_cpp_matches_golden(name: str) -> None:
    cell = load_cell(CATALOG / name)
    emitted = emit_cell(cell)
    assert emitted is not None
    expected = (GOLDEN / name / "main.cpp").read_text()
    assert emitted.files["main.cpp"] == expected


@pytest.mark.parametrize("name", _CELLS)
def test_cell_makefile_matches_golden(name: str) -> None:
    cell = load_cell(CATALOG / name)
    emitted = emit_cell(cell)
    assert emitted is not None
    expected = (GOLDEN / name / "Makefile").read_text()
    assert emitted.files["Makefile"] == expected


@pytest.mark.parametrize("name", _CELLS)
def test_emission_is_deterministic(name: str) -> None:
    cell = load_cell(CATALOG / name)
    a = emit_cell(cell)
    b = emit_cell(cell)
    assert a is not None and b is not None
    assert a.files == b.files
    assert a.csv_columns == b.csv_columns


@pytest.mark.parametrize("name", _CELLS)
def test_bundled_header_matches_catalog(name: str) -> None:
    cell = load_cell(CATALOG / name)
    emitted = emit_cell(cell)
    assert emitted is not None
    catalog_header = (CATALOG / name / "model" / "ams" / f"{name}.h").read_text()
    assert emitted.files[f"{name}.h"] == catalog_header


def test_emit_cell_returns_none_without_ams_model() -> None:
    # A structural-only cell ships no model/ams/.
    assert emit_cell(load_cell(DECOUPLING)) is None
    assert spec_from_cell(load_cell(DECOUPLING)) is None


def test_no_timestamp_in_emitted_sources() -> None:
    import re

    emitted = emit_cell(load_cell(NONINV))
    assert emitted is not None
    blob = "\n".join(emitted.files.values())
    assert "generated at" not in blob.lower()
    # No ISO-8601-ish date/time anywhere (emission is a pure function).
    assert not re.search(r"\d{4}-\d{2}-\d{2}", blob)


def test_columns_and_checks_shape() -> None:
    emitted = emit_cell(load_cell(NONINV))
    assert emitted is not None
    assert emitted.csv_columns == ("t", "IN", "OUT")
    names = [c.name for c in emitted.checks]
    assert "amplitude_ratio(IN->OUT)" in names
    assert "clipped_within(OUT)" in names

    x4 = emit_cell(load_cell(X4))
    assert x4 is not None
    assert x4.csv_columns == ("t", "IN1", "IN2", "IN3", "IN4", "OUT1", "OUT2", "OUT3", "OUT4")
    x4names = [c.name for c in x4.checks]
    for k in (1, 2, 3, 4):
        assert f"amplitude_ratio(IN{k}->OUT{k})" in x4names


def test_makefile_uses_env_seam() -> None:
    mk = emit_makefile("main.cpp", "sim")
    assert "SYSTEMC_HOME ?=" in mk
    assert "SYSTEMC_AMS_HOME ?=" in mk
    assert mk.startswith("# Generated by InferSynth")  # make comment, not //


# --------------------------------------------------------------------------- #
# Design-level structural emission.                                            #
# --------------------------------------------------------------------------- #
def _synthetic_design() -> Design:
    amp = Cell(
        "opamp-gain-noninverting",
        ports=[
            Port("IN", PortDirection.IN, PortKind.ELECTRICAL),
            Port("OUT", PortDirection.OUT, PortKind.ELECTRICAL),
            Port("VCC", PortDirection.IN, PortKind.POWER),
            Port("VEE", PortDirection.IN, PortKind.POWER),
            Port("GND", PortDirection.IN, PortKind.POWER),
        ],
        params=[Param("gain", "float")],
    )
    mystery = Cell(
        "mystery",
        ports=[
            Port("A", PortDirection.IN, PortKind.ELECTRICAL),
            Port("B", PortDirection.OUT, PortKind.ELECTRICAL),
        ],
    )
    d = Design(
        "demo",
        ports=[
            Port("IN_EXT", PortDirection.IN),
            Port("OUT_EXT", PortDirection.OUT),
            Port("VCC", PortDirection.IN, PortKind.POWER),
            Port("VEE", PortDirection.IN, PortKind.POWER),
            Port("GND", PortDirection.IN, PortKind.POWER),
            Port("SIN", PortDirection.IN),
            Port("SOUT", PortDirection.OUT),
        ],
    )
    d.add_instance("amp1", amp, {"gain": 10})
    d.add_instance("amp2", amp, {"gain": 4})
    d.add_instance("stub1", mystery)
    d.connect("vin", (BOUNDARY, "IN_EXT"), ("amp1", "IN"))
    d.connect("vmid", ("amp1", "OUT"), ("amp2", "IN"))
    d.connect("vout", ("amp2", "OUT"), (BOUNDARY, "OUT_EXT"))
    for r in ("VCC", "VEE", "GND"):
        d.connect(r.lower(), (BOUNDARY, r), ("amp1", r), ("amp2", r))
    d.connect("sin", (BOUNDARY, "SIN"), ("stub1", "A"))
    d.connect("sout", ("stub1", "B"), (BOUNDARY, "SOUT"))
    return d


def test_design_emission_wires_modeled_and_stubs_gap() -> None:
    el = elaborate(_synthetic_design())
    specs = {"opamp-gain-noninverting": spec_from_cell(load_cell(NONINV))}
    ed = emit_design(el, specs)

    top = ed.files["top.cpp"]
    # Both amps wired; the shared vmid net threads amp1.OUT into amp2.IN.
    assert "opamp_gain_noninverting amp1;" in top
    assert "opamp_gain_noninverting amp2;" in top
    assert "amp1.OUT(sig_net_vmid);" in top
    assert "amp2.IN(sig_net_vmid);" in top
    # One signal per net.
    assert "sig_net_vin" in top and "sig_net_vout" in top
    # The header is bundled for a hermetic build.
    assert "opamp-gain-noninverting.h" in ed.files

    # The gap is recorded and LOUD.
    assert not ed.report.complete
    assert [g[0] for g in ed.report.gaps] == ["stub1"]
    assert "!! STUB !!" in top
    rendered = ed.report.render()
    assert "STUBBED" in rendered
    assert "stub1" in rendered


def test_design_emission_is_deterministic() -> None:
    specs = {"opamp-gain-noninverting": spec_from_cell(load_cell(NONINV))}
    a = emit_design(elaborate(_synthetic_design()), specs)
    b = emit_design(elaborate(_synthetic_design()), specs)
    assert a.files == b.files


def test_design_all_modeled_reports_complete() -> None:
    # A design with only modeled instances has no gaps.
    amp = Cell(
        "opamp-gain-noninverting",
        ports=[
            Port("IN", PortDirection.IN, PortKind.ELECTRICAL),
            Port("OUT", PortDirection.OUT, PortKind.ELECTRICAL),
            Port("VCC", PortDirection.IN, PortKind.POWER),
            Port("VEE", PortDirection.IN, PortKind.POWER),
            Port("GND", PortDirection.IN, PortKind.POWER),
        ],
        params=[Param("gain", "float")],
    )
    d = Design(
        "solo",
        ports=[
            Port("I", PortDirection.IN),
            Port("O", PortDirection.OUT),
            Port("VCC", PortDirection.IN, PortKind.POWER),
            Port("VEE", PortDirection.IN, PortKind.POWER),
            Port("GND", PortDirection.IN, PortKind.POWER),
        ],
    )
    d.add_instance("a1", amp, {"gain": 2})
    d.connect("i", (BOUNDARY, "I"), ("a1", "IN"))
    d.connect("o", ("a1", "OUT"), (BOUNDARY, "O"))
    for r in ("VCC", "VEE", "GND"):
        d.connect(r.lower(), (BOUNDARY, r), ("a1", r))
    ed = emit_design(elaborate(d), {"opamp-gain-noninverting": spec_from_cell(load_cell(NONINV))})
    assert ed.report.complete
    assert "STUBBED" not in ed.report.render()


# --------------------------------------------------------------------------- #
# Toolchain probe (monkeypatched).                                             #
# --------------------------------------------------------------------------- #
def test_toolchain_absent_when_no_headers(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(tc_mod.shutil, "which", lambda _c: "/usr/bin/g++")
    monkeypatch.setattr(tc_mod, "_find_header_dir", lambda *_a, **_k: None)
    tchain = detect_toolchain(env={})
    assert not tchain.available
    assert any("SystemC" in r for r in tchain.reasons)
    assert "not found" in tchain.why_unavailable()


def test_toolchain_absent_when_no_compiler(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(tc_mod.shutil, "which", lambda _c: None)
    monkeypatch.setattr(tc_mod, "_find_header_dir", lambda *_a, **_k: "/opt/sc")
    tchain = detect_toolchain(env={})
    assert not tchain.available
    assert any("compiler" in r for r in tchain.reasons)


def test_toolchain_present_when_all_found(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(tc_mod.shutil, "which", lambda _c: "/usr/bin/g++")
    monkeypatch.setattr(tc_mod, "_find_header_dir", lambda *_a, **_k: "/opt/sc")
    tchain = detect_toolchain(env={"SYSTEMC_HOME": "/opt/sc", "SYSTEMC_AMS_HOME": "/opt/sc"})
    assert tchain.available
    assert tchain.cxx == "/usr/bin/g++"
    assert tchain.why_unavailable() == "toolchain available"


def test_real_probe_runs_on_this_machine() -> None:
    # Not asserting a value — just that the real probe returns a well-formed result.
    tchain = detect_toolchain()
    assert isinstance(tchain, AmsToolchain)
    assert isinstance(tchain.available, bool)


# --------------------------------------------------------------------------- #
# CSV parsing.                                                                  #
# --------------------------------------------------------------------------- #
def test_parse_csv_trace() -> None:
    text = "t,IN,OUT\n0.0,0.0,0.0\n1e-06,0.5,2.0\n"
    traces = parse_csv_trace(text)
    assert traces["t"] == [0.0, 1e-06]
    assert traces["IN"] == [0.0, 0.5]
    assert traces["OUT"] == [0.0, 2.0]


def test_parse_csv_trace_bad_width() -> None:
    with pytest.raises(tc_mod.AmsKernelError):
        parse_csv_trace("t,IN,OUT\n0.0,0.0\n")


# --------------------------------------------------------------------------- #
# The ams-simulation gate: two distinct loud skips.                            #
# --------------------------------------------------------------------------- #
def test_gate_skips_loud_when_no_ams_model() -> None:
    result = ams_simulation_cell_gate(load_cell(DECOUPLING))
    assert result.status == GateStatus.SKIPPED
    assert result.gate == AMS_GATE
    assert "no model/ams/" in result.diagnostics[0]
    assert "falls back to the v0" in result.diagnostics[0]


def test_gate_skips_loud_when_toolchain_absent(monkeypatch: pytest.MonkeyPatch) -> None:
    # Cell has a model, but force the toolchain absent.
    monkeypatch.setattr(
        "infersynth.gates.ams_simulation.detect_toolchain",
        lambda: AmsToolchain(available=False, reasons=("SystemC-AMS headers not found",)),
    )
    result = ams_simulation_cell_gate(load_cell(NONINV))
    assert result.status == GateStatus.SKIPPED
    assert result.gate == AMS_GATE
    assert "toolchain absent" in result.diagnostics[0]
    assert "SystemC-AMS headers not found" in result.diagnostics[0]


def test_gate_skip_wordings_are_distinct() -> None:
    no_model = ams_simulation_cell_gate(load_cell(DECOUPLING)).diagnostics[0]
    # The real machine has no toolchain, so this is the toolchain-absent skip.
    with_model = ams_simulation_cell_gate(load_cell(NONINV))
    assert with_model.status == GateStatus.SKIPPED
    assert no_model != with_model.diagnostics[0]


# --------------------------------------------------------------------------- #
# Real compile + run + cross-validate (skipped without a toolchain).           #
# --------------------------------------------------------------------------- #
@pytest.mark.sysc_ams
@pytest.mark.skipif(
    not detect_toolchain().available, reason="SystemC-AMS toolchain not installed"
)
def test_ams_matches_v0_tier() -> None:  # pragma: no cover - needs toolchain
    from infersynth.gates.simulation import run_cell_simulation

    cell = load_cell(NONINV)
    ams = ams_simulation_cell_gate(cell)
    assert ams.status == GateStatus.PASS
    # Cross-validate: the v0 tier passes the same operating point.
    v0_rows = run_cell_simulation(cell)
    assert all(ok for _, ok, _ in v0_rows)
