"""SystemC-AMS source emitter (WP-S2 deliverable 2): cell + design tiers.

Two entry points, both **pure text generation** (emit, don't bind — DESIGN.md
§4): the output is standalone SystemC-AMS C++ with no cppyy/PySysC dependency,
carrying no timestamps, so it is byte-stable and golden-comparable in CI.

* :func:`emit_cell` — a self-contained testbench ``main.cpp`` for one cell:
  drives a deterministic sine into each electrical input and a DC level onto each
  power rail, instantiates the cell's AMS TDF module with bound params, and
  records ``t`` + inputs + outputs to a CSV trace. Mirrors the v0 ``linear``
  scenario (docs/SIM.md §4) so the two tiers cross-validate at one operating
  point. Bundles the cell's committed ``model/ams/<cell>.h`` for a hermetic
  build, and a :func:`emit_makefile` build.
* :func:`emit_design` — a structural top ``top.cpp`` from an
  :class:`~infersynth.ir.elaborate.ElaboratedDesign`: one ``sca_signal`` per net,
  each instance's AMS module wired to its nets. Instances lacking an AMS model
  become a documented passthrough stub and are recorded LOUDLY in the
  :class:`EmissionReport` (graceful degradation, never silent — DESIGN.md §4).

The emitted CSV columns and the per-pair gain/rail checks the ``ams-simulation``
gate reads back are returned alongside the sources, so the gate reuses
``infersynth/sim/checks.py`` math rather than re-deriving it.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from infersynth.catalog.loader import CellPackage
from infersynth.emit_sysc_ams.spec import (
    AMS_RAIL_MARGIN,
    AmsModuleSpec,
    OperatingPoint,
    cxx_ident,
    format_double,
    operating_point,
    spec_from_cell,
)
from infersynth.ir.elaborate import ElaboratedDesign
from infersynth.sim.checks import Check, amplitude_ratio, clipped_within

__all__ = [
    "EmittedCell",
    "EmittedDesign",
    "EmissionReport",
    "emit_cell",
    "emit_design",
    "emit_makefile",
]

_GENERATED_BANNER = "// Generated by InferSynth emit_sysc_ams — do not edit."


# --------------------------------------------------------------------------- #
# Shared emitted TDF helper modules (stimulus + recorder).                     #
# --------------------------------------------------------------------------- #
_SOURCE_MODULES = """\
// Deterministic stimulus sources (stateless: pure functions of TDF time).
SCA_TDF_MODULE(is_sine_src)
{
    sca_tdf::sca_out<double> out;
    const double amplitude;
    const double freq_hz;
    const double offset;
    const double timestep_s;

    is_sine_src(sc_core::sc_module_name nm, double amplitude_, double freq_hz_,
                double offset_, double timestep_s_)
        : out("out"), amplitude(amplitude_), freq_hz(freq_hz_), offset(offset_),
          timestep_s(timestep_s_)
    {
    }

    void set_attributes() { set_timestep(timestep_s, sc_core::SC_SEC); }

    void processing()
    {
        const double t = get_time().to_seconds();
        out.write(offset + amplitude * std::sin(2.0 * M_PI * freq_hz * t));
    }
};

SCA_TDF_MODULE(is_dc_src)
{
    sca_tdf::sca_out<double> out;
    const double value;
    const double timestep_s;

    is_dc_src(sc_core::sc_module_name nm, double value_, double timestep_s_)
        : out("out"), value(value_), timestep_s(timestep_s_)
    {
    }

    void set_attributes() { set_timestep(timestep_s, sc_core::SC_SEC); }

    void processing() { out.write(value); }
};
"""


def _cxx_double(value: float) -> str:
    return format_double(value)


def _recorder_module(columns: tuple[str, ...]) -> str:
    """A bespoke CSV recorder with one sca_in per recorded column."""
    port_decls = "\n".join(
        f"    sca_tdf::sca_in<double> {c};" for c in columns
    )
    inits = ", ".join(f'{c}("{c}")' for c in columns)
    reads = ' << "," << '.join(f"{c}.read()" for c in columns)
    return f"""\
// CSV trace recorder: writes one row per timestep (no header row here).
SCA_TDF_MODULE(is_trace_recorder)
{{
{port_decls}
    std::ofstream &os;

    is_trace_recorder(sc_core::sc_module_name nm, std::ofstream &os_)
        : {inits}, os(os_)
    {{
    }}

    void processing()
    {{
        os << get_time().to_seconds() << "," << {reads} << "\\n";
    }}
}};
"""


# --------------------------------------------------------------------------- #
# Cell tier.                                                                    #
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class EmittedCell:
    """The emitted SystemC-AMS bundle + gate metadata for one cell."""

    cell_key: str
    files: dict[str, str]  # filename -> contents (main.cpp, Makefile, <cell>.h)
    csv_columns: tuple[str, ...]  # trace columns: ("t", <in...>, <out...>)
    checks: tuple[Check, ...]  # checks the gate applies to the parsed trace
    output_csv: str = "trace.csv"


def _cell_main_cpp(spec: AmsModuleSpec, op: OperatingPoint) -> tuple[str, tuple[str, ...]]:
    """Emit ``main.cpp`` for a cell; return (source, recorded-column names)."""
    recorded = spec.in_ports + spec.out_ports
    columns = ("t",) + recorded

    lines: list[str] = [
        _GENERATED_BANNER,
        f"// Cell testbench: {spec.cell_name}",
        "//",
        "// Drives a sine into each electrical input and a DC level onto each rail,",
        "// runs the AMS TDF module, and records t + inputs + outputs to CSV. The",
        "// operating point mirrors the v0 `linear` scenario (docs/SIM.md).",
        "#include <systemc-ams>",
        "#include <cmath>",
        "#include <fstream>",
        "#include <string>",
        f'#include "{spec.header}"',
        "",
        _SOURCE_MODULES,
        _recorder_module(recorded),
        "int sc_main(int argc, char *argv[])",
        "{",
        '    const std::string out_path = (argc > 1) ? argv[1] : "trace.csv";',
        "",
        "    // One signal per cell port.",
    ]
    for p in spec.ports:
        lines.append(f"    sca_tdf::sca_signal<double> sig_{p};")
    lines.append("")

    ts = _cxx_double(op.dt)
    amp = _cxx_double(op.amplitude)
    freq = _cxx_double(op.freq_hz)
    lines.append("    // Stimulus: a sine per input, a DC level per rail.")
    for p in spec.in_ports:
        lines.append(
            f'    is_sine_src src_{p}("src_{p}", {amp}, {freq}, 0.0, {ts});'
        )
        lines.append(f"    src_{p}.out(sig_{p});")
    for p in spec.power_ports:
        val = _cxx_double(op.rails.get(p, 0.0))
        lines.append(f'    is_dc_src src_{p}("src_{p}", {val}, {ts});')
        lines.append(f"    src_{p}.out(sig_{p});")
    lines.append("")

    # DUT instantiation: ctor args = gain params (sorted) then margin.
    ctor_vals = [_cxx_double(op.params[p]) for p in spec.ctor_params]
    ctor_vals.append(_cxx_double(op.margin))
    ctor_arg_str = ", ".join(['"dut"', *ctor_vals])
    lines.append("    // Device under test.")
    lines.append(f"    {spec.module} dut({ctor_arg_str});")
    for p in spec.ports:
        lines.append(f"    dut.{p}(sig_{p});")
    lines.append("")

    # Recorder.
    header_row = ",".join(columns)
    lines.append("    // CSV trace.")
    lines.append("    std::ofstream os(out_path.c_str());")
    lines.append(f'    os << "{header_row}\\n";')
    rec_binds = " ".join(f"rec.{p}(sig_{p});" for p in recorded)
    lines.append('    is_trace_recorder rec("rec", os);')
    lines.append(f"    {rec_binds}")
    lines.append("")

    total = _cxx_double(op.dt * op.n_steps)
    lines.append(f"    sc_core::sc_start({total}, sc_core::SC_SEC);")
    lines.append("    os.close();")
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines) + "\n", columns


def _cell_checks(spec: AmsModuleSpec, op: OperatingPoint) -> tuple[Check, ...]:
    """Gain + rail checks over the emitted trace, reusing sim/checks.py.

    Pairs the i-th input with the i-th output (sorted) and expects the i-th gain
    ctor param; asserts each output stays within the rails. This is the AMS-tier
    read of the v0 ``linear`` scenario's assertions.
    """
    checks: list[Check] = []
    lo = op.rails.get("VEE")
    hi = op.rails.get("VCC")
    n_pairs = min(len(spec.in_ports), len(spec.out_ports))
    for i in range(n_pairs):
        in_col = spec.in_ports[i]
        out_col = spec.out_ports[i]
        if i < len(spec.ctor_params):
            expected = op.params[spec.ctor_params[i]]
            checks.append(amplitude_ratio(in_col, out_col, expected=expected, tol_pct=1.0))
        if lo is not None and hi is not None:
            checks.append(clipped_within(out_col, lo, hi))
    return tuple(checks)


def emit_cell(cell: CellPackage) -> EmittedCell | None:
    """Emit the SystemC-AMS testbench bundle for *cell*, or ``None`` if no model.

    Returns ``None`` when the cell ships no ``model/ams/<cell>.h`` — the caller
    (the gate) turns that into a loud SKIP, distinct from a missing toolchain.
    """
    spec = spec_from_cell(cell)
    if spec is None:
        return None
    op = operating_point(cell, spec)
    main_cpp, columns = _cell_main_cpp(spec, op)
    files = {
        spec.header: spec.header_text,
        "main.cpp": main_cpp,
        "Makefile": emit_makefile("main.cpp", "sim"),
    }
    return EmittedCell(
        cell_key=cell.key,
        files=files,
        csv_columns=columns,
        checks=_cell_checks(spec, op),
    )


# --------------------------------------------------------------------------- #
# Design tier.                                                                  #
# --------------------------------------------------------------------------- #
@dataclass
class EmissionReport:
    """Records which instances got a real AMS module and which were stubbed."""

    modeled: list[tuple[str, str]] = field(default_factory=list)  # (path, cell)
    gaps: list[tuple[str, str, str]] = field(default_factory=list)  # (path, cell, reason)

    @property
    def complete(self) -> bool:
        return not self.gaps

    def render(self) -> str:
        lines = [f"AMS emission: {len(self.modeled)} modeled, {len(self.gaps)} stubbed"]
        for path, cell in self.modeled:
            lines.append(f"  [modeled] {path} ({cell})")
        for path, cell, reason in self.gaps:
            # Loud, per DESIGN.md §4: a stubbed instance is unverified, not verified.
            lines.append(f"  !! STUB !! {path} ({cell}): {reason}")
        if self.gaps:
            lines.append(
                f"!! {len(self.gaps)} instance(s) STUBBED — the emitted top is NOT a "
                "complete behavioral model !!"
            )
        return "\n".join(lines)


@dataclass(frozen=True)
class EmittedDesign:
    """The emitted structural top + its emission report."""

    design_name: str
    files: dict[str, str]  # filename -> contents (top.cpp, Makefile, headers)
    report: EmissionReport


def _net_signal_name(net: str) -> str:
    return f"net_{cxx_ident(net)}"


def emit_design(
    design: ElaboratedDesign,
    specs: dict[str, AmsModuleSpec],
) -> EmittedDesign:
    """Emit a structural SystemC-AMS top for *design*.

    *specs* maps IR cell name -> :class:`AmsModuleSpec` for cells that carry an
    AMS model. Instances whose cell is absent from *specs* are emitted as a
    documented passthrough stub and recorded in the report.
    """
    report = EmissionReport()

    # (instance_path, port) -> net name.
    pin_net: dict[tuple[str, str], str] = {}
    for net_name, pins in design.nets.items():
        for inst_path, port in pins:
            pin_net[(inst_path, port)] = net_name

    used_headers: dict[str, str] = {}
    members: list[str] = []  # module member declarations
    ctor_inits: list[str] = []  # initializer-list entries
    body: list[str] = []  # port binding statements + stub notes

    for path in sorted(design.instances):
        inst = design.instances[path]
        cell_name = inst.cell.name
        ident = cxx_ident(path)
        spec = specs.get(cell_name)
        if spec is None:
            report.gaps.append(
                (path, cell_name, "no AMS model (model/ams/) — emitted as passthrough stub")
            )
            body.append(
                f"// !! STUB !! instance {path} ({cell_name}) has no AMS model; "
                "wire its nets through by hand or add model/ams/."
            )
            continue

        report.modeled.append((path, cell_name))
        used_headers[spec.header] = spec.header_text

        ctor_vals: list[str] = []
        for pname in spec.ctor_params:
            val = inst.params.get(pname)
            ctor_vals.append(_cxx_double(float(val)) if val is not None else "1.0")
        ctor_vals.append(_cxx_double(AMS_RAIL_MARGIN))
        ctor_arg_str = ", ".join([f'"{ident}"', *ctor_vals])
        members.append(f"    {spec.module} {ident};")
        ctor_inits.append(f"{ident}({ctor_arg_str})")
        for port in spec.ports:
            net = pin_net.get((path, port))
            if net is None:
                body.append(f"// {ident}.{port} is unconnected (no net)")
            else:
                body.append(f"{ident}.{port}(sig_{_net_signal_name(net)});")

    top = cxx_ident(design.name) + "_top"
    lines: list[str] = [
        _GENERATED_BANNER,
        f"// Structural top for design: {design.name}",
        "//",
        "// One sca_signal per net; each instance's AMS module is a member wired to",
        "// its nets in the constructor. Stubbed instances (no AMS model) are flagged",
        "// inline and in the emission report.",
        "#include <systemc-ams>",
    ]
    for header in sorted(used_headers):
        lines.append(f'#include "{header}"')
    lines.append("")
    lines.append(f"SC_MODULE({top})")
    lines.append("{")
    for net in sorted(design.nets):
        lines.append(f"    sca_tdf::sca_signal<double> sig_{_net_signal_name(net)};")
    if members:
        lines.append("")
        lines.extend(members)
    lines.append("")
    if ctor_inits:
        lines.append(f"    SC_CTOR({top})")
        lines.append("        : " + ", ".join(ctor_inits))
        lines.append("    {")
    else:
        lines.append(f"    SC_CTOR({top})")
        lines.append("    {")
    lines.extend(f"        {b}" for b in body)
    lines.append("    }")
    lines.append("};")
    lines.append("")
    top_cpp = "\n".join(lines) + "\n"

    files = {"top.cpp": top_cpp, "Makefile": emit_makefile("top.cpp", "top")}
    files.update(used_headers)
    return EmittedDesign(design_name=design.name, files=files, report=report)


# --------------------------------------------------------------------------- #
# Build.                                                                        #
# --------------------------------------------------------------------------- #
def emit_makefile(src: str, target: str) -> str:
    """A Makefile that compiles *src* against SystemC + SystemC-AMS.

    Include/library paths come from the ``SYSTEMC_HOME`` / ``SYSTEMC_AMS_HOME``
    environment variables (the documented seam) with conventional defaults.
    """
    return f"""\
# Generated by InferSynth emit_sysc_ams — do not edit.
# SystemC-AMS build. Override paths via the environment:
#   make SYSTEMC_HOME=/opt/systemc SYSTEMC_AMS_HOME=/opt/systemc-ams
SYSTEMC_HOME ?= /usr/local/systemc
SYSTEMC_AMS_HOME ?= /usr/local/systemc-ams
CXX ?= g++
CXXSTD ?= -std=c++17
CXXFLAGS ?= $(CXXSTD) -I. -I$(SYSTEMC_HOME)/include -I$(SYSTEMC_AMS_HOME)/include
LDFLAGS ?= -L$(SYSTEMC_HOME)/lib -L$(SYSTEMC_HOME)/lib-linux64 \\
	-L$(SYSTEMC_AMS_HOME)/lib -L$(SYSTEMC_AMS_HOME)/lib-linux64 \\
	-Wl,-rpath,$(SYSTEMC_HOME)/lib -Wl,-rpath,$(SYSTEMC_HOME)/lib-linux64 \\
	-Wl,-rpath,$(SYSTEMC_AMS_HOME)/lib -Wl,-rpath,$(SYSTEMC_AMS_HOME)/lib-linux64
LDLIBS ?= -lsystemc-ams -lsystemc -lm

TARGET = {target}
SRC = {src}

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS) $(LDLIBS)

.PHONY: run clean
run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET) trace.csv
"""
